### ISSUE TITLE
Error using mod in 1.15.2 server

### ISSUE THREAD

**Issue by DarkenLM** [Thutmose/Thut-Elevators#17]
Hello. I was trying to add your mod (v1.15.2-8.0.2) to a server I have, but it have me this error:
```
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Thut Crafts (thutcrafts) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
        Thut Elevators (thuttech) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
        Thut Core (thutcore) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
[m[1;31m[17:11:47] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Utilizador\Desktop\Minecraft\Server\Server 1.15.2 forge\.\crash-reports\crash-2020-03-13_17.11.47-server.txt
[m[32m[17:11:47] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[m[32m[17:11:47] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[m[1;31m[17:11:47] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:549) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
```
What's happening?

**Comment by Thutmose** [comment]
closing this one since it is posted here: https://github.com/Thutmose/Thut/issues/167
